"""Utilities for the convex optimization programming project."""

from .lp import (
    OTLinearProgram,
    OTLPSolution,
    build_ot_lp,
    build_transport_equality_constraints,
    flatten_plan,
    marginal_violation,
    solve_ot_lp,
    solve_ot_lp_ipm,
    solve_ot_lp_pdlp,
    solve_ot_lp_simplex,
    transport_cost,
    unflatten_plan,
)
from .pdhg import (
    OTPDHGConfig,
    OTPDHGHistory,
    OTPDHGSolution,
    default_pdhg_step_sizes,
    ot_operator_norm,
    recommended_ot_pdhg_config,
    solve_ot_lp_pdhg_numpy,
)
from .entropic_ot import (
    OTEntropicHistory,
    OTEntropicSolution,
    OTSinkhornConfig,
    entropic_transport_objective,
    gibbs_kernel,
    solve_entropic_ot,
    solve_entropic_ot_ipm,
    solve_entropic_ot_sinkhorn_numpy,
    solve_entropic_ot_sinkhorn_pot,
)
from .gaussian_ot import GaussianW2Result, covariance_ellipse_patch, gaussian_w2_squared
from .plotting import METHOD_STYLES, apply_project_style
from .problem_setup import (
    GaussianSpec,
    OTInstance,
    default_gaussian_specs,
    generate_ot_instance,
    sample_gaussian_points,
    squared_euclidean_cost_matrix,
    uniform_weights,
    validate_ot_instance,
)
from .quadratic_ot import (
    OTADMMConfig,
    OTQuadraticHistory,
    OTQuadraticSolution,
    project_onto_marginal_affine_set,
    quadratic_transport_objective,
    recommended_admm_rho,
    solve_quadratic_ot,
    solve_quadratic_ot_admm,
    solve_quadratic_ot_ipm,
)
from .visualization import CouplingDisplayStats, draw_coupling_panel, shared_point_cloud_limits

__all__ = [
    "CouplingDisplayStats",
    "GaussianSpec",
    "GaussianW2Result",
    "OTADMMConfig",
    "OTEntropicHistory",
    "OTEntropicSolution",
    "OTInstance",
    "OTLinearProgram",
    "OTLPSolution",
    "OTPDHGConfig",
    "OTPDHGHistory",
    "OTPDHGSolution",
    "OTQuadraticHistory",
    "OTQuadraticSolution",
    "OTSinkhornConfig",
    "METHOD_STYLES",
    "apply_project_style",
    "build_ot_lp",
    "build_transport_equality_constraints",
    "covariance_ellipse_patch",
    "default_gaussian_specs",
    "default_pdhg_step_sizes",
    "draw_coupling_panel",
    "entropic_transport_objective",
    "flatten_plan",
    "gaussian_w2_squared",
    "generate_ot_instance",
    "gibbs_kernel",
    "marginal_violation",
    "ot_operator_norm",
    "project_onto_marginal_affine_set",
    "quadratic_transport_objective",
    "recommended_admm_rho",
    "recommended_ot_pdhg_config",
    "sample_gaussian_points",
    "shared_point_cloud_limits",
    "solve_ot_lp",
    "solve_ot_lp_ipm",
    "solve_ot_lp_pdlp",
    "solve_ot_lp_pdhg_numpy",
    "solve_ot_lp_simplex",
    "solve_quadratic_ot",
    "solve_quadratic_ot_admm",
    "solve_quadratic_ot_ipm",
    "solve_entropic_ot",
    "solve_entropic_ot_ipm",
    "solve_entropic_ot_sinkhorn_numpy",
    "solve_entropic_ot_sinkhorn_pot",
    "squared_euclidean_cost_matrix",
    "transport_cost",
    "unflatten_plan",
    "uniform_weights",
    "validate_ot_instance",
]
